<?xml version = "1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot">


      <xacro:property name="base_length" value="0.1" />
      <xacro:property name="base_width" value="0.16" />
      <xacro:property name="base_height" value="0.2" />
      <xacro:property name="wheel_separation_length" value="0.048" />
      <xacro:property name="wheel_separation_width" value="0.077" />
      <xacro:property name="wheel_radius" value="0.044" />
      <xacro:property name="wheel_length" value="0.05" />
      <xacro:property name="laser_radius" value="0.075" />
      <link name="base_footprint"/>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <material name="green"/> 
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
    </collision>
    <xacro:box_inertia m="5.0" l="${base_length}" w="${base_width}" h="${base_height}" xyz="0 0 0" rpy="0 0 0"/>
  </link>

  <joint name="base_dummy_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <!-- Wheels -->
   <link name="lf">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    <xacro:cylinder_inertia m="5.0" r="${wheel_radius}" h="${wheel_length}" xyz="0 0 0" rpy="0 0 0"/>
  </link>

  <link name="lb">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    <xacro:cylinder_inertia m="5.0" r="${wheel_radius}" h="${wheel_length}" xyz="0 0 0" rpy="0 0 0"/>
  </link>
  <link name="rf">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    <xacro:cylinder_inertia m="5.0" r="${wheel_radius}" h="${wheel_length}" xyz="0 0 0" rpy="0 0 0"/>
  </link>
   <link name="rb">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    <xacro:cylinder_inertia m="5.0" r="${wheel_radius}" h="${wheel_length}" xyz="0 0 0" rpy="0 0 0"/>
  </link>

  <joint name="base_lf" type="continuous">
    <parent link="base_link"/>
    <child link="lf"/>
    <origin xyz="${wheel_separation_length} ${wheel_separation_width} 0" rpy="${pi/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <joint name="base_lb" type="continuous">
    <parent link="base_link"/>
    <child link="lb"/>
    <origin xyz="${-wheel_separation_length} ${wheel_separation_width} 0" rpy="${pi/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <joint name="base_rf" type="continuous">
    <parent link="base_link"/>
    <child link="rf"/>
    <origin xyz="${wheel_separation_length} ${-wheel_separation_width} 0" rpy="${pi/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <joint name="base_rb" type="continuous">
    <parent link="base_link"/>
    <child link="rb"/>
    <origin xyz="${-wheel_separation_length} ${-wheel_separation_width} 0" rpy="${pi/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>


  <!-- Laser -->
  <link name="laser_frame">
    <visual>
      <geometry>
        <cylinder radius="${laser_radius}" length="${wheel_length}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${laser_radius}" length="${wheel_length}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    <xacro:cylinder_inertia m="0.5" r="${laser_radius}" h="${wheel_length}" xyz="0 0 0" rpy="${pi/2} 0 0"/>
  </link>

  <joint name="laser_joint" type="fixed">
    <parent link="base_link"/>
    <child link="laser_frame"/>
    <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
  </joint>

</robot>