<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot">

  <material name="green">
    <color rgba="0 0.5 0 1"/>
  </material>
  <material name="blue">
    <color rgba="0 0 0.5 1"/>
  </material>

  <!-- Constants -->
  <xacro:property name="base_length" value="0.1" />
  <xacro:property name="base_width" value="0.16" />
  <xacro:property name="base_height" value="0.2" />
  <xacro:property name="wheel_separation_length" value="${0.095/2}" />
  <xacro:property name="wheel_separation_width" value="${0.154/2}" />
  <xacro:property name="wheel_radius" value="0.044" />
  <xacro:property name="wheel_length" value="0.05" />
  <xacro:property name="laser_radius" value="0.075" />

  <link name="base_footprint"/>
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <material name="green"/> 
    </visual>
  </link>

  <link name="LF">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>
  </link>

  <link name="LB">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>
  </link>

  <joint name="base_dummy_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <joint name="base_LF" type="continuous">
    <parent link="base_link"/>
    <child link="LF"/>
    <origin xyz="${wheel_separation_length} ${wheel_separation_width} 0" rpy="${pi/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>
  <joint name="base_LB" type="continuous">
    <parent link="base_link"/>
    <child link="LB"/>
    <origin xyz="${-wheel_separation_length} ${wheel_separation_width} 0" rpy="${pi/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="RF">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="blue"/>
    </visual>
  </link>
   <link name="RB">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="blue"/>
    </visual>
  </link>

  <joint name="base_RF" type="continuous">
    <parent link="base_link"/>
    <child link="RF"/>
    <origin xyz="${wheel_separation_length} ${-wheel_separation_width} 0 " rpy="${pi/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>
  <joint name="base_RB" type="continuous">
    <parent link="base_link"/>
    <child link="RB"/>
    <origin xyz="${-wheel_separation_length} ${-wheel_separation_width} 0 " rpy="${pi/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="laser_frame">
    <visual>
      <geometry>
        <cylinder radius="${laser_radius}" length="${wheel_length}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="blue"/>
    </visual>
  </link>

  <joint name="laser_joint" type="fixed">
        <parent link="base_link"/>
        <child link="laser_frame"/>
        <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
    </joint>

</robot>
